let bugs = [
  {
    "id": 1,
    "file-name": "common_butterfly",
    "name": {
      "name-USen": "common butterfly",
      "name-EUen": "common butterfly",
      "name-EUde": "Kohlweißling",
      "name-EUes": "mariposa común",
      "name-USes": "mariposa común",
      "name-EUfr": "piéride de la rave",
      "name-USfr": "piéride de la rave",
      "name-EUit": "farfalla comune",
      "name-EUnl": "koolwitje",
      "name-CNzh": "白粉蝶",
      "name-TWzh": "白粉蝶",
      "name-JPja": "モンシロチョウ",
      "name-KRko": "배추흰나비",
      "name-EUru": "белянка"
    },
    "availability": {
      "month-northern": "9-6",
      "month-southern": "3-12",
      "time": "4am - 7pm",
      "isAllDay": false,
      "isAllYear": false,
      "location": "Flying",
      "rarity": "Common",
      "month-array-northern": [9, 10, 11, 12, 1, 2, 3, 4, 5, 6],
      "month-array-southern": [3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      "time-array": [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
    },
    "price": 160,
    "price-flick": 240,
    "catch-phrase": "I caught a common butterfly! They often flutter by!",
    "museum-phrase": "The common butterfly would have you believe it is but a beautiful friend flitting prettily about the flowers. Bah, I say! They may seem innocent things with their pretty white wings, but they hide a dark side! The common butterfly caterpillar is called a cabbage worm, you see, and it's a most voracious pest. The ravenous beasts chew through cabbage, broccoli, kale and the like with a devastating gusto. And my feathers! Their green coloring is truly GROSS! A hoo-rrific hue, I say.",
    "image_uri": "https://acnhapi.com/v1/images/bugs/1",
    "icon_uri": "https://acnhapi.com/v1/icons/bugs/1"
  },
  {
    "id": 2,
    "file-name": "yellow_butterfly",
    "name": {
      "name-USen": "yellow butterfly",
      "name-EUen": "yellow butterfly",
      "name-EUde": "Zitronenfalter",
      "name-EUes": "mariposa colias",
      "name-USes": "mariposa colias",
      "name-EUfr": "citrin",
      "name-USfr": "citrin",
      "name-EUit": "farfalla gialla",
      "name-EUnl": "citroenvlinder",
      "name-CNzh": "斑缘点粉蝶",
      "name-TWzh": "斑緣點粉蝶",
      "name-JPja": "モンキチョウ",
      "name-KRko": "노랑나비",
      "name-EUru": "желтушка"
    },
    "availability": {
      "month-northern": "3-6 & 9-10",
      "month-southern": "9-12 & 3-4",
      "time": "4am - 7pm",
      "isAllDay": false,
      "isAllYear": false,
      "location": "Flying",
      "rarity": "Common",
      "month-array-northern": [3, 4, 5, 6, 9, 10],
      "month-array-southern": [9, 10, 11, 12, 3, 4],
      "time-array": [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
    },
    "price": 160,
    "price-flick": 240,
    "catch-phrase": "I caught a yellow butterfly! Shouldn't all BUTTERflies be yellow?",
    "museum-phrase": "Allow me to enlighten you... The yellow butterfly is named for its yellow wings. Need I say more? If I must, then allow me to note that the female yellow butterfly can lay up to 600 eggs at a time! Bleech! And their creepy crawly caterpillars just love to chomp on clover plants. A recipe for disaster, I say. Just imagine reaching for a four-leaf clover, only to touch a larva instead! Yuck! The worst of luck!",
    "image_uri": "https://acnhapi.com/v1/images/bugs/2",
    "icon_uri": "https://acnhapi.com/v1/icons/bugs/2"
  },
  {
    "id": 3,
    "file-name": "tiger_butterfly",
    "name": {
      "name-USen": "tiger butterfly",
      "name-EUen": "tiger butterfly",
      "name-EUde": "Schwalbenschwanz",
      "name-EUes": "mariposa tigre",
      "name-USes": "mariposa tigre",
      "name-EUfr": "machaon",
      "name-USfr": "machaon",
      "name-EUit": "farfalla tigre",
      "name-EUnl": "koninginnenpage",
      "name-CNzh": "凤蝶",
      "name-TWzh": "鳳蝶",
      "name-JPja": "アゲハチョウ",
      "name-KRko": "호랑나비",
      "name-EUru": "махаон"
    },
    "availability": {
      "month-northern": "3-9",
      "month-southern": "9-3",
      "time": "4am - 7pm",
      "isAllDay": false,
      "isAllYear": false,
      "location": "Flying",
      "rarity": "Common",
      "month-array-northern": [3, 4, 5, 6, 7, 8, 9],
      "month-array-southern": [9, 10, 11, 12, 1, 2, 3],
      "time-array": [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
    },
    "price": 240,
    "price-flick": 360,
    "catch-phrase": "I caught a tiger butterfly! I've earned my stripes!",
    "museum-phrase": "Tiger butterflies are known for their majestic wings, which many consider quite beautiful. Truth be told, I find them monstrous! Those strange striped patterns... They give this owl the goose bumps! And while you may imagine young tiger butterfly larvae to look like lovely green caterpillars...it's not so! Why, when tiger butterflies are but babes, they're covered in unsightly white, brown, and black spots. In this way, they camouflage themselves as...as...bird droppings! Putrid pests, indeed!",
    "image_uri": "https://acnhapi.com/v1/images/bugs/3",
    "icon_uri": "https://acnhapi.com/v1/icons/bugs/3"
  },
  {
    "id": 4,
    "file-name": "peacock_butterfly",
    "name": {
      "name-USen": "peacock butterfly",
      "name-EUen": "peacock butterfly",
      "name-EUde": "Ritterfalter",
      "name-EUes": "mariposa bianor",
      "name-USes": "mariposa bianor",
      "name-EUfr": "papilio bianor",
      "name-USfr": "papilio bianor",
      "name-EUit": "farfalla vanessa io",
      "name-EUnl": "pauwenpage",
      "name-CNzh": "乌鸦凤蝶",
      "name-TWzh": "烏鴉鳳蝶",
      "name-JPja": "カラスアゲハ",
      "name-KRko": "제비나비",
      "name-EUru": "бианор"
    },
    "availability": {
      "month-northern": "3-6",
      "month-southern": "9-12",
      "time": "4am - 7pm",
      "isAllDay": false,
      "isAllYear": false,
      "location": "Flying near hybrid flowers",
      "rarity": "Uncommon",
      "month-array-northern": [3, 4, 5, 6],
      "month-array-southern": [9, 10, 11, 12],
      "time-array": [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
    },
    "price": 2500,
    "price-flick": 3750,
    "catch-phrase": "I caught a peacock butterfly! Now it's my turn to strut my stuff!",
    "museum-phrase": "Pretty as a peacock? Bah, I say! The wings of the peacock butterfly may have a pattern similar to that of the beautiful bird... But its forewings are also often covered in a dark, velvety hair! You heard right! HAIRY wings! A hair-raising revelation indeed!",
    "image_uri": "https://acnhapi.com/v1/images/bugs/4",
    "icon_uri": "https://acnhapi.com/v1/icons/bugs/4"
  },
  {
    "id": 5,
    "file-name": "common_bluebottle",
    "name": {
      "name-USen": "common bluebottle",
      "name-EUen": "common bluebottle",
      "name-EUde": "Kolibrifalter",
      "name-EUes": "mariposa triángulo azul",
      "name-USes": "mariposa triángulo azul",
      "name-EUfr": "graphium sarpedon",
      "name-USfr": "graphium sarpedon",
      "name-EUit": "graphium sarpedon",
      "name-EUnl": "blauwe driehoek",
      "name-CNzh": "青带凤蝶",
      "name-TWzh": "青帶鳳蝶",
      "name-JPja": "アオスジアゲハ",
      "name-KRko": "청띠제비나비",
      "name-EUru": "графиум сарпедон"
    },
    "availability": {
      "month-northern": "4-8",
      "month-southern": "9-2",
      "time": "4am - 7pm",
      "isAllDay": false,
      "isAllYear": false,
      "location": "Flying",
      "rarity": "Common",
      "month-array-northern": [4, 5, 6, 7, 8],
      "month-array-southern": [9, 10, 11, 12, 1, 2],
      "time-array": [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
    },
    "price": 300,
    "price-flick": 450,
    "catch-phrase": "I caught a common bluebottle! I'll put it in a rare green jar!",
    "museum-phrase": "The common bluebottle is a type of swallowtail butterfly with a bright blue line running down its wings. They fly quite nimbly, it seems, and are thus quite difficult to catch. But seeing how they've been known to slurp nutrients from MUD puddles... I simply CAN'T imagine wanting to catch one myself. What awful breath!",
    "image_uri": "https://acnhapi.com/v1/images/bugs/5",
    "icon_uri": "https://acnhapi.com/v1/icons/bugs/5"
  },
  {
    "id": 6,
    "file-name": "paper_kite_butterfly",
    "name": {
      "name-USen": "paper kite butterfly",
      "name-EUen": "paper kite butterfly",
      "name-EUde": "Weiße Baumnymphe",
      "name-EUes": "mariposa cometa de papel",
      "name-USes": "mariposa papel de arroz",
      "name-EUfr": "grand planeur",
      "name-USfr": "grand planeur",
      "name-EUit": "farfalla carta di riso",
      "name-EUnl": "papiervlinder",
      "name-CNzh": "大白斑蝶",
      "name-TWzh": "大白斑蝶",
      "name-JPja": "オオゴマダラ",
      "name-KRko": "왕얼룩나비",
      "name-EUru": "идея левконоя"
    },
    "availability": {
      "month-northern": "",
      "month-southern": "",
      "time": "8am - 7pm",
      "isAllDay": false,
      "isAllYear": true,
      "location": "Flying",
      "rarity": "Common",
      "month-array-northern": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      "month-array-southern": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      "time-array": [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
    },
    "price": 1000,
    "price-flick": 1500,
    "catch-phrase": "I caught a paper kite butterfly! Do I read it, fly it, or spreadit on toast?",
    "museum-phrase": "With its black-and-white-striped wing pattern, the paper kite butterfly is both elegant and pretty... PRETTY POISONOUS I MEAN! Hoo dear! Where was I? Oh yes... Even this butterfly's black-and-white-striped larva and little golden pupae are toxic to predators. Indeed, the paper kite butterfly's foul flavor is famous, and thus birds, in particular, steer clear of the fiends. THIS bird most of all!",
    "image_uri": "https://acnhapi.com/v1/images/bugs/6",
    "icon_uri": "https://acnhapi.com/v1/icons/bugs/6"
  },
  {
    "id": 7,
    "file-name": "great_purple_emperor",
    "name": {
      "name-USen": "great purple emperor",
      "name-EUen": "great purple emperor",
      "name-EUde": "Japan-Schillerfalter",
      "name-EUes": "marip. emperador japonés",
      "name-USes": "marip. emperador japonés",
      "name-EUfr": "sasakia charonda",
      "name-USfr": "grand empereur pourpre",
      "name-EUit": "farfalla imperatore viola",
      "name-EUnl": "paarse keizervlinder",
      "name-CNzh": "大紫蛱蝶",
      "name-TWzh": "大紫蛺蝶",
      "name-JPja": "オオムラサキ",
      "name-KRko": "왕오색나비",
      "name-EUru": "сасакия харонда"
    },
    "availability": {
      "month-northern": "5-8",
      "month-southern": "11-2",
      "time": "4am - 7pm",
      "isAllDay": false,
      "isAllYear": false,
      "location": "Flying",
      "rarity": "Rare",
      "month-array-northern": [5, 6, 7, 8],
      "month-array-southern": [11, 12, 1, 2],
      "time-array": [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
    },
    "price": 3000,
    "price-flick": 4500,
    "catch-phrase": "I caught a great purple emperor! Its purple reign is over now!",
    "museum-phrase": "The great purple emperor lives high in the treetops and is renowned for its pretty purple-hued wings. Its impressive bird-like wingspan and elusive nature have made it a favorite among butterfly aficionados. But truth be told, the so-called great purple emperor has some not-so-great personal peculiarities. For one...it has two horrid HORNS upon its head when it is in its caterpillar form. For two...it has been known to dine on feces and animal carcasses! Hoo! That's why I call it the Emperor of EWWW!",
    "image_uri": "https://acnhapi.com/v1/images/bugs/7",
    "icon_uri": "https://acnhapi.com/v1/icons/bugs/7"
  },
  {
    "id": 8,
    "file-name": "monarch_butterfly",
    "name": {
      "name-USen": "monarch butterfly",
      "name-EUen": "monarch butterfly",
      "name-EUde": "Monarchfalter",
      "name-EUes": "mariposa monarca",
      "name-USes": "mariposa monarca",
      "name-EUfr": "monarque",
      "name-USfr": "monarque",
      "name-EUit": "farfalla monarca",
      "name-EUnl": "monarchvlinder",
      "name-CNzh": "大桦斑蝶",
      "name-TWzh": "大樺斑蝶",
      "name-JPja": "オオカバマダラ",
      "name-KRko": "왕나비",
      "name-EUru": "монарх"
    },
    "availability": {
      "month-northern": "9-11",
      "month-southern": "3-5",
      "time": "4am - 5pm",
      "isAllDay": false,
      "isAllYear": false,
      "location": "Flying",
      "rarity": "Common",
      "month-array-northern": [9, 10, 11],
      "month-array-southern": [3, 4, 5],
      "time-array": [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
    },
    "price": 140,
    "price-flick": 210,
    "catch-phrase": "I caught a monarch butterfly! Guess the butterflies are a democracy now!",
    "museum-phrase": "Did you know the monarch butterfly migrates south for the winter and returns north for the summer? Indeed, these horrid orange beasties do not tolerate the cold and travel 3,000 miles to escape the winter. During the journey, they cluster together in trees by the thousands just to stay warm. Imagine! Hordes of the foul flittering fiends huddled together in one place! If only they'd put on tiny coats instead.",
    "image_uri": "https://acnhapi.com/v1/images/bugs/8",
    "icon_uri": "https://acnhapi.com/v1/icons/bugs/8"
  },
  {
    "id": 9,
    "file-name": "emperor_butterfly",
    "name": {
      "name-USen": "emperor butterfly",
      "name-EUen": "emperor butterfly",
      "name-EUde": "Himmelsfalter",
      "name-EUes": "mariposa celeste",
      "name-USes": "mariposa celeste",
      "name-EUfr": "morpho bleu",
      "name-USfr": "morpho bleu",
      "name-EUit": "farfalla morfo blu",
      "name-EUnl": "blauwe morpho",
      "name-CNzh": "大蓝闪蝶",
      "name-TWzh": "大藍閃蝶",
      "name-JPja": "モルフォチョウ",
      "name-KRko": "몰포나비",
      "name-EUru": "морфо менелай"
    },
    "availability": {
      "month-northern": "6-9 & 12-3",
      "month-southern": "6-9 & 12-3",
      "time": "5pm - 8am",
      "isAllDay": false,
      "isAllYear": false,
      "location": "Flying",
      "rarity": "Uncommon",
      "month-array-northern": [6, 7, 8, 9, 12, 1, 2, 3],
      "month-array-southern": [6, 7, 8, 9, 12, 1, 2, 3],
      "time-array": [17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7]
    },
    "price": 4000,
    "price-flick": 6000,
    "catch-phrase": "I caught an emperor butterfly! It's not your average monarch!",
    "museum-phrase": "The emperor butterfly is called the jewel of the forest. But its vivid blue hue... Ewww, let me tell you! The color does not come from a dye, but rather from light reflecting off layers of translucent scales. Yes, butterfly wings are covered in tiny scales! SCALES! Butterfly? Bah! More like snake of the sky!",
    "image_uri": "https://acnhapi.com/v1/images/bugs/9",
    "icon_uri": "https://acnhapi.com/v1/icons/bugs/9"
  },
  {
    "id": 10,
    "file-name": "agrias_butterfly",
    "name": {
      "name-USen": "agrias butterfly",
      "name-EUen": "agrias butterfly",
      "name-EUde": "Agrias-Falter",
      "name-EUes": "mariposa narciso",
      "name-USes": "mariposa narciso",
      "name-EUfr": "agrias",
      "name-USfr": "agrias",
      "name-EUit": "farfalla agrias",
      "name-EUnl": "agriasvlinder",
      "name-CNzh": "彩袄蛱蝶",
      "name-TWzh": "彩襖蛺蝶",
      "name-JPja": "ミイロタテハ",
      "name-KRko": "아그리아스나비",
      "name-EUru": "агриас клаудина"
    },
    "availability": {
      "month-northern": "4-9",
      "month-southern": "10-3",
      "time": "8am - 5pm",
      "isAllDay": false,
      "isAllYear": false,
      "location": "Flying",
      "rarity": "Uncommon",
      "month-array-northern": [4, 5, 6, 7, 8, 9],
      "month-array-southern": [10, 11, 12, 1, 2, 3],
      "time-array": [8, 9, 10, 11, 12, 13, 14, 15, 16]
    },
    "price": 3000,
    "price-flick": 4500,
    "catch-phrase": "I caught an agrias butterfly! I wonder if it finds me disagrias-able?",
    "museum-phrase": "Some say the agrias butterfly is one of the most beautiful butterflies in the world. Bah, I say! BAH! They may have brightly colored wings, but the way they flutter and flitter...SO FOUL! In fact, the agrias butterfly flies so fast, it is quite a feat to catch one. I suppose I should congratulate you on your good fortune... But catching any bug seems a misfortune to me.",
    "image_uri": "https://acnhapi.com/v1/images/bugs/10",
    "icon_uri": "https://acnhapi.com/v1/icons/bugs/10"
  },
  {
    "id": 11,
    "file-name": "rajah_brookes_birdwing",
    "name": {
      "name-USen": "Rajah Brooke's birdwing",
      "name-EUen": "Rajah Brooke's birdwing",
      "name-EUde": "Troides brookiana",
      "name-EUes": "mariposa alas de Brooke",
      "name-USes": "mariposa alas de Brooke",
      "name-EUfr": "troides brookiana",
      "name-USfr": "troides brookiana",
      "name-EUit": "farfalla Raja Brooke",
      "name-EUnl": "Rajah Brooke-vlinder",
      "name-CNzh": "红颈凤蝶",
      "name-TWzh": "紅頸鳳蝶",
      "name-JPja": "アカエリトリバネアゲハ",
      "name-KRko": "붉은목도리비단나비",
      "name-EUru": "трогоноптера Брука"
    },
    "availability": {
      "month-northern": "4-9 & 12-2",
      "month-southern": "6-8 & 10-3",
      "time": "8am - 5pm",
      "isAllDay": false,
      "isAllYear": false,
      "location": "Flying",
      "rarity": "Uncommon",
      "month-array-northern": [4, 5, 6, 7, 8, 9, 12, 1, 2],
      "month-array-southern": [6, 7, 8, 10, 11, 12, 1, 2, 3],
      "time-array": [8, 9, 10, 11, 12, 13, 14, 15, 16]
    },
    "price": 2500,
    "price-flick": 3750,
    "catch-phrase": "I caught a Rajah Brooke's birdwing! Nothing else I'd rajah be doing!",
    "museum-phrase": "Did you know that the repulsive Rajah Brooke's birdwing loves to luxuriate in hot-springs water? It's true! Hoo! The males gather in groups to sip the moisture while the females hide in jungle trees. And though they dress to impress in red and green, these fluttering fiends are not just stylish... They're also quite malicious! Their little larvae pack a poisonous punch that's supposed to protect them from predators... But I suspect more diabolical designs.",
    "image_uri": "https://acnhapi.com/v1/images/bugs/11",
    "icon_uri": "https://acnhapi.com/v1/icons/bugs/11"
  },
  {
    "id": 12,
    "file-name": "queen_alexandras_birdwing",
    "name": {
      "name-USen": "Queen Alexandra's birdwing",
      "name-EUen": "Queen Alexandra's birdwing",
      "name-EUde": "Vogelfalter",
      "name-EUes": "mariposa alas de pájaro",
      "name-USes": "mariposa alas de pájaro",
      "name-EUfr": "troides alexandrae",
      "name-USfr": "troides alexandrae",
      "name-EUit": "farfalla regina Alessandra",
      "name-EUnl": "Alexandra's vogelvlinder",
      "name-CNzh": "亚历山大凤蝶",
      "name-TWzh": "亞歷山大鳳蝶",
      "name-JPja": "アレキサンドラトリバネアゲハ",
      "name-KRko": "알렉산드라비단제비나비",
      "name-EUru": "птицекрылка Александры"
    },
    "availability": {
      "month-northern": "5-9",
      "month-southern": "11-3",
      "time": "8am - 4pm",
      "isAllDay": false,
      "isAllYear": false,
      "location": "Flying",
      "rarity": "Rare",
      "month-array-northern": [5, 6, 7, 8, 9],
      "month-array-southern": [11, 12, 1, 2, 3],
      "time-array": [8, 9, 10, 11, 12, 13, 14, 15]
    },
    "price": 4000,
    "price-flick": 6000,
    "catch-phrase": "I caught a Queen Alexandra's birdwing! That's a feather in my cap!",
    "museum-phrase": "Hoo! The horror! This behemoth butterfly may be called a Queen Alexandra's birdwing... But I call it the Queen of My Nightmares! It is huge! Indeed, the world's hugest. No butterfly can best its foot-long wingspan. The larvae alone grow to more than 4 inches. As if that weren't appalling enough...they're poisonous! Murderous monsters, indeed!",
    "image_uri": "https://acnhapi.com/v1/images/bugs/12",
    "icon_uri": "https://acnhapi.com/v1/icons/bugs/12"
  },
  {
    "id": 13,
    "file-name": "moth",
    "name": {
      "name-USen": "moth",
      "name-EUen": "moth",
      "name-EUde": "Motte",
      "name-EUes": "polilla",
      "name-USes": "polilla",
      "name-EUfr": "papillon de nuit",
      "name-USfr": "papillon de nuit",
      "name-EUit": "falena",
      "name-EUnl": "mot",
      "name-CNzh": "飞蛾",
      "name-TWzh": "飛蛾",
      "name-JPja": "ガ",
      "name-KRko": "나방",
      "name-EUru": "павлиноглазка"
    },
    "availability": {
      "month-northern": "",
      "month-southern": "",
      "time": "7pm - 4am",
      "isAllDay": false,
      "isAllYear": true,
      "location": "Flying by light",
      "rarity": "Common",
      "month-array-northern": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      "month-array-southern": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      "time-array": [19, 20, 21, 22, 23, 0, 1, 2, 3]
    },
    "price": 130,
    "price-flick": 195,
    "catch-phrase": "I caught a moth! And I had a ball doing it!",
    "museum-phrase": "Many think the moth is strictly a nocturnal creature. Alas, no! These frightful fluttering beasts have been known to haunt the daylight and twilight hours too. Thus, there is no time of day one might escape the moth trait I dislike most of all—those feathery antennae! The mere thought of them gives my feathers goosebumps. And I'm no goose.",
    "image_uri": "https://acnhapi.com/v1/images/bugs/13",
    "icon_uri": "https://acnhapi.com/v1/icons/bugs/13"
  },
  {
    "id": 14,
    "file-name": "atlas_moth",
    "name": {
      "name-USen": "Atlas moth",
      "name-EUen": "Atlas moth",
      "name-EUde": "Atlasspinner",
      "name-EUes": "polilla atlas",
      "name-USes": "polilla atlas",
      "name-EUfr": "attacus Atlas",
      "name-USfr": "attacus Atlas",
      "name-EUit": "farfalla cobra",
      "name-EUnl": "atlasvlinder",
      "name-CNzh": "皇蛾",
      "name-TWzh": "皇蛾",
      "name-JPja": "ヨナグニサン",
      "name-KRko": "아틀라스나방",
      "name-EUru": "павлиноглазка атлас"
    },
    "availability": {
      "month-northern": "4-9",
      "month-southern": "10-3",
      "time": "7pm - 4am",
      "isAllDay": false,
      "isAllYear": false,
      "location": "On trees",
      "rarity": "Uncommon",
      "month-array-northern": [4, 5, 6, 7, 8, 9],
      "month-array-southern": [10, 11, 12, 1, 2, 3],
      "time-array": [19, 20, 21, 22, 23, 0, 1, 2, 3]
    },
    "price": 3000,
    "price-flick": 4500,
    "catch-phrase": "I caught an Atlas moth! I bet it never gets lost!",
    "museum-phrase": "The Atlas moth is a monstrous thing! Not only is it one of the largest moths in the world... The tips of its wings look rather like the heads of venomous snakes! Despite its largeness and loathsome looks, the adult Atlas moth lives only for a few days. It emerges from its cocoon without a mouth, you see...and so cannot eat. I feel for the poor thing...but it is still foul!",
    "image_uri": "https://acnhapi.com/v1/images/bugs/14",
    "icon_uri": "https://acnhapi.com/v1/icons/bugs/14"
  },
  {
    "id": 15,
    "file-name": "madagascan_sunset_moth",
    "name": {
      "name-USen": "Madagascan sunset moth",
      "name-EUen": "Madagascan sunset moth",
      "name-EUde": "Regenbogenfalter",
      "name-EUes": "polilla crepuscular",
      "name-USes": "polilla crepuscular",
      "name-EUfr": "chrysiridia rhipheus",
      "name-USfr": "adriandolo",
      "name-EUit": "urania del Madagascar",
      "name-EUnl": "adriandolo",
      "name-CNzh": "日落蛾",
      "name-TWzh": "日落蛾",
      "name-JPja": "ニシキオオツバメガ",
      "name-KRko": "마다가스카르비단제비나방",
      "name-EUru": "урания мадагаскарская"
    },
    "availability": {
      "month-northern": "4-9",
      "month-southern": "10-3",
      "time": "8am - 4pm",
      "isAllDay": false,
      "isAllYear": false,
      "location": "Flying",
      "rarity": "Uncommon",
      "month-array-northern": [4, 5, 6, 7, 8, 9],
      "month-array-southern": [10, 11, 12, 1, 2, 3],
      "time-array": [8, 9, 10, 11, 12, 13, 14, 15]
    },
    "price": 2500,
    "price-flick": 3750,
    "catch-phrase": "I caught a Madagascan sunset moth! Wow, you're not from around here!",
    "museum-phrase": "The Madagascan sunset moth is said to be the most beautiful moth in the world...a sentiment even I can't deny. While most moths are nocturnal, this one flutters about during the day, making good use of the light. That is, when the daylight reflects off its wings, a kaleidoscope of colors are revealed! Oh! Eh...too bad it has such startling red feet as a caterpillar. I might have found it almost tolerable otherwise. Almost, but not quite.",
    "image_uri": "https://acnhapi.com/v1/images/bugs/15",
    "icon_uri": "https://acnhapi.com/v1/icons/bugs/15"
  },
  {
    "id": 16,
    "file-name": "long_locust",
    "name": {
      "name-USen": "long locust",
      "name-EUen": "long locust",
      "name-EUde": "Nasenschrecke",
      "name-EUes": "langosta alargada",
      "name-USes": "langosta alargada",
      "name-EUfr": "acrida cinerea",
      "name-USfr": "acrida cinerea",
      "name-EUit": "acrida cinerea",
      "name-EUnl": "veldsprinkhaan",
      "name-CNzh": "中华剑角蝗",
      "name-TWzh": "中華劍角蝗",
      "name-JPja": "ショウリョウバッタ",
      "name-KRko": "방아깨비",
      "name-EUru": "акрида"
    },
    "availability": {
      "month-northern": "4-11",
      "month-southern": "10-5",
      "time": "8am - 7pm",
      "isAllDay": false,
      "isAllYear": false,
      "location": "On the ground",
      "rarity": "Common",
      "month-array-northern": [4, 5, 6, 7, 8, 9, 10, 11],
      "month-array-southern": [10, 11, 12, 1, 2, 3, 4, 5],
      "time-array": [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
    },
    "price": 200,
    "price-flick": 300,
    "catch-phrase": "I caught a long locust! Or, as I call it, a looooocust.",
    "museum-phrase": "As if the average locust weren't large enough...we must suffer the long locust too! The wretched beasts are known for their unusually long hind legs as well as their elongated heads. But that is hardly the long locusts' worst trait... I tell you, they spit brown goo when they're scared!",
    "image_uri": "https://acnhapi.com/v1/images/bugs/16",
    "icon_uri": "https://acnhapi.com/v1/icons/bugs/16"
  },
  {
    "id": 17,
    "file-name": "migratory_locust",
    "name": {
      "name-USen": "migratory locust",
      "name-EUen": "migratory locust",
      "name-EUde": "Wanderschrecke",
      "name-EUes": "langosta migratoria",
      "name-USes": "langosta migratoria",
      "name-EUfr": "criquet pèlerin",
      "name-USfr": "criquet pèlerin",
      "name-EUit": "locusta migratoria",
      "name-EUnl": "treksprinkhaan",
      "name-CNzh": "飞蝗",
      "name-TWzh": "飛蝗",
      "name-JPja": "トノサマバッタ",
      "name-KRko": "섬풀무치",
      "name-EUru": "перелетная саранча"
    },
    "availability": {
      "month-northern": "8-11",
      "month-southern": "2-5",
      "time": "8am - 7pm",
      "isAllDay": false,
      "isAllYear": false,
      "location": "On the ground",
      "rarity": "Uncommon",
      "month-array-northern": [8, 9, 10, 11],
      "month-array-southern": [2, 3, 4, 5],
      "time-array": [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
    },
    "price": 600,
    "price-flick": 900,
    "catch-phrase": "I caught a migratory locust! Things just went south for this guy!",
    "museum-phrase": "Ah yes, the lone migratory locust. It seems like such a harmless hopper as it bounces about in the grass. But beware! When these pests band together and travel in swarms, they leave devastation in their wake! Migratory locusts have gathered by the millions throughout history, wiping out crops and causing famine. That's why I always say, \"Never let a locust hang out with its friends!\". That is precisely how a plague begins.",
    "image_uri": "https://acnhapi.com/v1/images/bugs/17",
    "icon_uri": "https://acnhapi.com/v1/icons/bugs/17"
  },
  {
    "id": 18,
    "file-name": "rice_grasshopper",
    "name": {
      "name-USen": "rice grasshopper",
      "name-EUen": "rice grasshopper",
      "name-EUde": "Heuschrecke",
      "name-EUes": "langosta",
      "name-USes": "langosta",
      "name-EUfr": "criquet",
      "name-USfr": "criquet",
      "name-EUit": "locusta",
      "name-EUnl": "rijstsprinkhaan",
      "name-CNzh": "稻蝗",
      "name-TWzh": "稻蝗",
      "name-JPja": "イナゴ",
      "name-KRko": "메뚜기",
      "name-EUru": "рисовая кобылка"
    },
    "availability": {
      "month-northern": "8-11",
      "month-southern": "2-5",
      "time": "8am - 7pm",
      "isAllDay": false,
      "isAllYear": false,
      "location": "On the ground",
      "rarity": "Common",
      "month-array-northern": [8, 9, 10, 11],
      "month-array-southern": [2, 3, 4, 5],
      "time-array": [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
    },
    "price": 400,
    "price-flick": 600,
    "catch-phrase": "I caught a rice grasshopper! I've been looking for agluten-free alternative...",
    "museum-phrase": "In point of fact, rice grasshoppers are an awful pest! They devour rice plants and wipe out the crucial crop. But revenge is sweet! These bugs are edible, you see, and so some folks eat them as way to get rid of them. When boiled in soy sauce, rice grasshoppers are quite tasty, it's said. Though why anyone would put an insect in their mouth is beyond me. The mere thought gives me the gags!",
    "image_uri": "https://acnhapi.com/v1/images/bugs/18",
    "icon_uri": "https://acnhapi.com/v1/icons/bugs/18"
  },
  {
    "id": 19,
    "file-name": "grasshopper",
    "name": {
      "name-USen": "grasshopper",
      "name-EUen": "grasshopper",
      "name-EUde": "Grashüpfer",
      "name-EUes": "saltamontes",
      "name-USes": "saltamontes",
      "name-EUfr": "sauterelle",
      "name-USfr": "sauterelle",
      "name-EUit": "cavalletta",
      "name-EUnl": "sprinkhaan",
      "name-CNzh": "蚱蜢",
      "name-TWzh": "蚱蜢",
      "name-JPja": "キリギリス",
      "name-KRko": "여치",
      "name-EUru": "кузнечик"
    },
    "availability": {
      "month-northern": "7-9",
      "month-southern": "1-3",
      "time": "8am - 5pm",
      "isAllDay": false,
      "isAllYear": false,
      "location": "On the ground",
      "rarity": "Common",
      "month-array-northern": [7, 8, 9],
      "month-array-southern": [1, 2, 3],
      "time-array": [8, 9, 10, 11, 12, 13, 14, 15, 16]
    },
    "price": 160,
    "price-flick": 240,
    "catch-phrase": "I caught a grasshopper! They're a grass act!",
    "museum-phrase": "Grasshoppers are known for making a \"chirping\" sound. Though it doesn't sound like chirping to me... They make this rude racket by rubbing their hind legs against their wings. And though they eat seeds and pollen, they sometimes prey on smaller insects too. I say! Such violent table manners should not be tolerated! Horrible hoppers.",
    "image_uri": "https://acnhapi.com/v1/images/bugs/19",
    "icon_uri": "https://acnhapi.com/v1/icons/bugs/19"
  },
  {
    "id": 20,
    "file-name": "cricket",
    "name": {
      "name-USen": "cricket",
      "name-EUen": "cricket",
      "name-EUde": "Grille",
      "name-EUes": "grillo común",
      "name-USes": "grillo común",
      "name-EUfr": "grillon des prés",
      "name-USfr": "grillon des prés",
      "name-EUit": "grillo",
      "name-EUnl": "krekel",
      "name-CNzh": "蟋蟀",
      "name-TWzh": "蟋蟀",
      "name-JPja": "コオロギ",
      "name-KRko": "귀뚜라미",
      "name-EUru": "сверчок"
    },
    "availability": {
      "month-northern": "9-11",
      "month-southern": "3-5",
      "time": "5pm - 8am",
      "isAllDay": false,
      "isAllYear": false,
      "location": "On the ground",
      "rarity": "Common",
      "month-array-northern": [9, 10, 11],
      "month-array-southern": [3, 4, 5],
      "time-array": [17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7]
    },
    "price": 130,
    "price-flick": 195,
    "catch-phrase": "I caught a cricket! What a chirp thrill!",
    "museum-phrase": "I say, where shall I start with the cricket? Well, to begin with, they are mostly nocturnal creatures. And for that you day-loving diurnal types should be grateful! Hoo! It means you don't have to lay eyes upon their prickly legs or overly long antennae like us night owls! Of course, crickets are best known for the chirping sound they make by rubbing their wings together. Some find the noise lovely to listen to. Alas, it only serves to remind me of another unpleasant fact... Which is to say...you will find a cricket's ears right next to its knees! I've gone weak in the knees at the mention of it!",
    "image_uri": "https://acnhapi.com/v1/images/bugs/20",
    "icon_uri": "https://acnhapi.com/v1/icons/bugs/20"
  },
]

export default bugs;
